theme = "catppuccin_frappe"

[editor]
line-number = "relative"
true-color = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.lsp]
display-messages = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
