[lanuage-server.julia]
command = "julia"
args = [
    "--startup-file=no",
    "--history-file=no",
    "~/.config/helix/julia-lsp.jl"
]

[[language]]
name = "julia"
scope = "source.julia"
injection-regex = "julia"
file-types = ["jl"]
roots = ["Project.toml", "Manifest.toml"]
comment-token = "#"
language-servers = ["julia"]
indent = { tab-width = 4, unit = "    " }
